### PR TITLE
OpenAPI: Fix API calls pointing to subpath

### LINKED ISSUE #1137: Provider does not work when you run grafana on a sub path: example.com/grafana
### Terraform Version
* Terraform: 1.5.3
* Terraform Grafana Provider: 2.5.0
* Grafana: 10.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
* All

### Terraform Configuration Files

```hcl
provider "grafana" {
  url  = "https://monitor.example.com/grafana"
  auth = var.grafana_auth
}
resource "grafana_folder" "folder" {
  title = "test"
}
```

### Debug Output
```
    Error: failed to create folder: Post "https://monitor.example.com/api/folders": status: 404, body: <html>
    <head><title>404 Not Found</title></head>
    <body>
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.25.2</center>
    </body>
    </html>
  
  
      with module.this.grafana_folder.folder,
      on .terraform/modules/this/src/redacted/redacted/redacted/grafana.tf line 1, in resource "grafana_folder" "folder":

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

The folder should be created

### Actual Behavior

An error occurs because the provdier is attempting to talk to the api at `https://monitor.example.com/api/folders` which is invalid. The correct api url is `https://monitor.example.com/grafana/api/folders`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

### PR DESCRIPTION
**Pull request by julienduchesne**
Closes https://github.com/grafana/terraform-provider-grafana/issues/1137
Currently, the test suite is pointing to a subpath BUT Grafana redirects from the root to the subpath
The provider is badly configured but the tests still pass because of the redirect

To fix the test suite, I add a nginx proxy in this PR, so that calling the host directly fails and you have to go through the subpath

I've also reworked the Makefile so that it has more common args (less repetition of configs), so it's harder to make a mistake

### CODE REVIEW

File: internal/provider/provider.go [hunk 1]
```diff
@@ -438,7 +442,7 @@ func createGrafanaOAPIClient(apiURL string, d *schema.ResourceData) (*goapi.Graf
 
 	cfg := goapi.TransportConfig{
 		Host:         u.Host,
-		BasePath:     "/api",
+		BasePath:     apiPath,
```
Comment (julienduchesne) [inline internal/provider/provider.go:445]: The actual fix is here

**Review by K-Phoen — APPROVED** [review]
