### PR TITLE
Dashboard Resource Works with Grafana 8

### LINKED ISSUE #212: Dashboard resource not working with Grafana v8
### Terraform Version
* Terraform: 0.14.10
* Terraform Grafana Provider: 1.11.0
* Grafana: 8.0.0

### Affected Resource(s)
* grafana_dashboard

### Terraform Configuration Files
```hcl

```

### Expected Behavior
Existing dashboards should keep working after migrating from Grafana v7 to v8
New dashboards should be created in Grafana v8

### Actual Behavior
What actually happened?

Grafana 8 has removed from the API the slug id > https://github.com/grafana/grafana/pull/35104
So when upgrading to Grafana v8 this provider basically stops working.

This is blocking upgrading Grafana to v8

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

For existing resources > After upgrading Grafana from version 7 to 8, on first apply it shows a version mismatch and try to recreate the dashboard,

```Error: status: 412, body: {"message":"The dashboard has been changed by someone else","status":"version-mismatch"}```

then it fails because the dashboard already exists with the same name.

```Error: status: 412, body: {"message":"A dashboard with the same name in the folder already exists","status":"name-exists"}```

For new resources it creates the dashboard but it fails to store the resource into the terraform state, I guess because the API is not accepting/returning the slug anymore

```
Error: Provider produced inconsistent result after apply

When applying changes to module.k8s_grafana.grafana_dashboard.metrics[0],
provider "registry.terraform.io/grafana/grafana" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

As solution we had to rollback Grafana to v7 and remove manually affected dashboards , recreating them again with terraform

### Important Factoids
none

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/grafana/terraform-provider-grafana/issues/95
- https://github.com/grafana/grafana/pull/35104

### PR DESCRIPTION
**Pull request by trotttrotttrott**
[Grafana 8 removed `slug` endpoints](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#breaking-changes) that have been deprecated since Grafana 5. My proposed fix is to:

* Deprecate the `slug` field in the provider.
* Add `uid` and use it as we were using `slug`.
* Use the read and delete endpoints that have replaced the slug endpoints.

Other changes:

* Drone will run acceptance tests with Grafana 8.0.2.
* Test configurations were moved to `examples/`. This is a convention I'd like to propose we adopt for all acceptance test configuration files. Moving them into dedicated `.tf` files allows us to take advantage of `terrform fmt`, syntax highlighting, and use them in documentation. I've prefixed these particular examples with `_acc_` to indicate they are used in acceptance tests only because they would not make good examples for documentation.
* `version` was added as a computed (read only) field. This field is removed if set as a static value in `config_json`. It cannot be managed as a static value. Therefore we manage it in state and set it on read.
* `TestAccDashboard_disappear` removed. This does not seem useful.
* 404 on read and delete fixed. The error message read as if it were removing it from state, but instead it was throwing, `Error: status: 404, body: {"message":"Dashboard not found"}` without removing it. It now displays a warning error stating that Terraform will attempt to recreate it.
* `func prepareDashboardModel(configJSON string) map[string]interface{}` replaced with `func makeDashboard(d *schema.ResourceData) gapi.Dashboard`. This function name and signature is consistent with other resources in this provider.

Closes https://github.com/grafana/terraform-provider-grafana/issues/212

### CODE REVIEW

File: grafana/provider_test.go [hunk 1]
```diff
@@ -74,3 +73,14 @@ func testAccPreCheck(t *testing.T) {
 		}
 	})
 }
+
+// testAccExample returns an example config from the examples directory.
+// Examples are used for both documentation and acceptance tests.
+func testAccExample(t *testing.T, path string) string {
```
Comment (julienduchesne) [inline grafana/provider_test.go:78]: I like this. Much better than defining hcl into strings

File: grafana/resource_dashboard.go [hunk 2]
```diff
@@ -68,39 +86,32 @@ func ResourceDashboard() *schema.Resource {
...
 	return ReadDashboard(ctx, d, meta)
 }
 
 func ReadDashboard(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
 	client := meta.(*client).gapi
-
-	slug := d.Id()
-
-	dashboard, err := client.Dashboard(slug)
+	uid := d.Id()
```
Comment (julienduchesne) [inline grafana/resource_dashboard.go:174]: Won't the ID change make this fail when migrating from the old version to the new one? The ID stored in the state is the slug, it will try to `DashboardByUID` with a slug, which won't work, and then it will remove all dashboards from state since it won't find them

I think it might be nice to have an actual tfstate from a version before this one and use that to have a migration acceptance test

File: grafana/provider_test.go [hunk 3]
```diff
@@ -74,3 +73,14 @@ func testAccPreCheck(t *testing.T) {
...
+	path = fmt.Sprintf("../examples/%s", path)
+	example, err := ioutil.ReadFile(path)
```
Comment (inkel) [inline grafana/provider_test.go]: Nit: 
```suggestion
	example, err := ioutil.ReadFile("../examples/" + path)
```

There's no actual need for `fmt.Sprintf` here, and it will definitely be much faster:

```
BenchmarkCreateSimpleString/Sprintf-12         	14443981	        79.73 ns/op	      24 B/op	       1 allocs/op
BenchmarkCreateSimpleString/plus-12            	1000000000	         0.6006 ns/op	       0 B/op	       0 allocs/op
```

**Review by inkel — APPROVED** [review]
Love the changes, thanks!

File: grafana/resource_dashboard.go (hunk 2 above)
Comment (trotttrotttrott) [reply grafana/resource_dashboard.go:174]: Darn, you're right. I thought this seemed too easy. I'm able to reproduce this. I'm going to see if I can add a [StateUpgrader](https://www.terraform.io/docs/extend/resources/state-migration.html).

I'm not thrilled about committing raw state for acceptance tests. Seems to me we'll only need such tests to ensure _this_ PR works. I think I'll start by documenting in fine detail how I've tested once I get a StateUpgrader working. We can decide from there if it makes sense to commit something we should maintain beyond this.

**Comment by trotttrotttrott** [comment]
Per [@julienduchesne's comment](https://github.com/grafana/terraform-provider-grafana/pull/217#discussion_r653437169), I've added a StateUpgrader to make a smooth transition from slug to UID.

<details>
<summary>I used the following configuration to test this:</summary>

```hcl
terraform {
  required_providers {
    grafana = {
      source = "grafana/grafana"
    }
  }
}

provider "grafana" {
  url  = "http://localhost:3001"
  auth = "admin:admin"
}

resource "grafana_dashboard" "defines_uid" {
  config_json = <<EOD
{
  "title": "Defines UID",
  "uid": "defined-uid"
}
EOD
}

resource "grafana_dashboard" "no_uid" {
  config_json = <<EOD
{
  "title": "No UID"
}
EOD
}

resource "grafana_dashboard" "defines_slug" {
  config_json = <<EOD
{
  "title": "Defines Slug",
  "slug": "defined-slug"
}
EOD
}

resource "grafana_dashboard" "defines_slug_and_uid" {
  config_json = <<EOD
{
  "title": "Defines Slug and UID",
  "slug": "defined-slug",
  "uid": "defined-uid-in-addition-to-slug"
}
EOD
}
```

</details>

I first applied this configuration using the 1.11.0.

<details>
<summary>Execution plan output without the StateUpgrader produced:</summary>

```
grafana_dashboard.defines_slug_and_uid: Refreshing state... [id=defines-slug-and-uid]
grafana_dashboard.defines_uid: Refreshing state... [id=defines-uid]
grafana_dashboard.defines_slug: Refreshing state... [id=defines-slug]
grafana_dashboard.no_uid: Refreshing state... [id=no-uid]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # grafana_dashboard.no_uid has been deleted
  - resource "grafana_dashboard" "no_uid" {
      - config_json  = jsonencode(
            {
              - title = "No UID"
            }
        ) -> null
      - dashboard_id = 1 -> null
      - folder       = 0 -> null
      - id           = "no-uid" -> null
      - slug         = "no-uid" -> null
    }
  # grafana_dashboard.defines_slug has been deleted
  - resource "grafana_dashboard" "defines_slug" {
      - config_json  = jsonencode(
            {
              - slug  = "defined-slug"
              - title = "Defines Slug"
            }
        ) -> null
      - dashboard_id = 4 -> null
      - folder       = 0 -> null
      - id           = "defines-slug" -> null
      - slug         = "defines-slug" -> null
    }
  # grafana_dashboard.defines_slug_and_uid has been deleted
  - resource "grafana_dashboard" "defines_slug_and_uid" {
      - config_json  = jsonencode(
            {
              - slug  = "defined-slug"
              - title = "Defines Slug and UID"
            }
        ) -> null
      - dashboard_id = 2 -> null
      - folder       = 0 -> null
      - id           = "defines-slug-and-uid" -> null
      - slug         = "defines-slug-and-uid" -> null
    }
  # grafana_dashboard.defines_uid has been deleted
  - resource "grafana_dashboard" "defines_uid" {
      - config_json  = jsonencode(
            {
              - title = "Defines UID"
            }
        ) -> null
      - dashboard_id = 3 -> null
      - folder       = 0 -> null
      - id           = "defines-uid" -> null
      - slug         = "defines-uid" -> null
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to
undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_dashboard.defines_slug will be created
  + resource "grafana_dashboard" "defines_slug" {
      + config_json  = jsonencode(
            {
              + slug  = "defined-slug"
              + title = "Defines Slug"
            }
        )
      + dashboard_id = (known after apply)
      + id           = (known after apply)
      + slug         = (known after apply)
      + uid          = (known after apply)
      + version      = (known after apply)
    }

  # grafana_dashboard.defines_slug_and_uid will be created
  + resource "grafana_dashboard" "defines_slug_and_uid" {
      + config_json  = jsonencode(
            {
              + slug  = "defined-slug"
              + title = "Defines Slug and UID"
              + uid   = "defined-uid-in-addition-to-slug"
            }
        )
      + dashboard_id = (known after apply)
      + id           = (known after apply)
      + slug         = (known after apply)
      + uid          = (known after apply)
      + version      = (known after apply)
    }

  # grafana_dashboard.defines_uid will be created
  + resource "grafana_dashboard" "defines_uid" {
      + config_json  = jsonencode(
            {
              + title = "Defines UID"
              + uid   = "defined-uid"
            }
        )
      + dashboard_id = (known after apply)
      + id           = (known after apply)
      + slug         = (known after apply)
      + uid          = (known after apply)
      + version      = (known after apply)
    }

  # grafana_dashboard.no_uid will be created
  + resource "grafana_dashboard" "no_uid" {
      + config_json  = jsonencode(
            {
              + title = "No UID"
            }
        )
      + dashboard_id = (known after apply)
      + id           = (known after apply)
      + slug         = (known after apply)
      + uid          = (known after apply)
      + version      = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.
╷
│ Warning: Dashboard "defines-uid" is in state, but no longer exists in grafana
│
│   with grafana_dashboard.defines_uid,
│   on main.tf line 14, in resource "grafana_dashboard" "defines_uid":
│   14: resource "grafana_dashboard" "defines_uid" {
│
│ "defines-uid" will be recreated when you apply
╵
╷
│ Warning: Dashboard "no-uid" is in state, but no longer exists in grafana
│
│   with grafana_dashboard.no_uid,
│   on main.tf line 23, in resource "grafana_dashboard" "no_uid":
│   23: resource "grafana_dashboard" "no_uid" {
│
│ "no-uid" will be recreated when you apply
╵
╷
│ Warning: Dashboard "defines-slug" is in state, but no longer exists in grafana
│
│   with grafana_dashboard.defines_slug,
│   on main.tf line 31, in resource "grafana_dashboard" "defines_slug":
│   31: resource "grafana_dashboard" "defines_slug" {
│
│ "defines-slug" will be recreated when you apply
╵
╷
│ Warning: Dashboard "defines-slug-and-uid" is in state, but no longer exists in grafana
│
│   with grafana_dashboard.defines_slug_and_uid,
│   on main.tf line 40, in resource "grafana_dashboard" "defines_slug_and_uid":
│   40: resource "grafana_dashboard" "defines_slug_and_uid" {
│
│ "defines-slug-and-uid" will be recreated when you apply
╵

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

</details>

The execution plan with the StateUpgrader shows no changes.

**Review by julienduchesne — APPROVED** [review]
