### PR TITLE
Fix permadiffs arising from default values in grafana_rule_group

### LINKED ISSUE #948: Permadiff when creating grafana_rule_group without intervalMs and maxDataPoints fields
### Terraform Version
* Terraform: 1.5.1
* Terraform Grafana Provider: 1.41.0
* Grafana: N/A (Cloud version, at time of writing)

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

### Terraform Configuration Files
```hcl
resource "grafana_rule_group" "test_group_1" {
  provider   = grafana.my_stack

  name = "Test 1"
    folder_uid = grafana_folder.my_folder.uid
    interval_seconds = 60
    org_id = 1

    rule {
        name = "Test 1"
        condition = "A"
        for = "0s"

        data {
            datasource_uid = "__expr__"
            ref_id = "A"
            relative_time_range {
                from = 0
                to = 0
            }
            model = jsonencode({
                expression = "90 > 70"
                type = "math"
                refId = "A"
            })
        }
    }
}
```

### Expected Behavior
What should have happened?

When running `terraform plan`, there should be no diff.

### Actual Behavior
What actually happened?

The following diff is produced:
```
Terraform will perform the following actions:

  # grafana_rule_group.test_group_1 will be updated in-place
  ~ resource "grafana_rule_group" "test_group_1" {
        id               = "a89db30c-ae41-4b31-98c4-f0027f70b0df;Test 1"
        name             = "Test 1"
        # (3 unchanged attributes hidden)

      ~ rule {
            name           = "Test 1"
            # (8 unchanged attributes hidden)

          ~ data {
              ~ model          = jsonencode(
                  ~ {
                      - intervalMs    = 1000
                      - maxDataPoints = 43200
                        # (3 unchanged attributes hidden)
                    }
                )
                # (2 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

For posterity, the Terraform state contains this:
```
                    "model": "{\"expression\":\"90 \\u003e 70\",\"intervalMs\":1000,\"maxDataPoints\":43200,\"refId\":\"A\",\"type\":\"math\"}",
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### PR DESCRIPTION
**Pull request by stevesg**
This change omits the `intervalMs` and `maxDataPoints` fields from the state, if they are set to the default values. This avoids permadiffs when the user does not explicitly specify the values, but just wants the default values.

Fixes #948 

<details><summary>`terraform plan` before fix:</summary>

```
Terraform will perform the following actions:

  # grafana_rule_group.test_group_1 will be updated in-place
  ~ resource "grafana_rule_group" "test_group_1" {
        id               = "a89db30c-ae41-4b31-98c4-f0027f70b0df;Test 1"
        name             = "Test 1"
        # (3 unchanged attributes hidden)

      ~ rule {
            name           = "Test 1"
            # (8 unchanged attributes hidden)

          ~ data {
              ~ model          = jsonencode(
                  ~ {
                      - intervalMs    = 1000
                      - maxDataPoints = 43200
                        # (3 unchanged attributes hidden)
                    }
                )
                # (2 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
</details>

<details><summary>`terraform plan` after fix:</summary>

```
No changes. Your infrastructure matches the configuration.
```
</summary>

### CODE REVIEW

File: internal/resources/grafana/resource_alerting_rule_group.go [hunk 1]
```diff
@@ -129,9 +129,11 @@ This resource requires Grafana 9.1.0 or later.
 										Description: "An optional identifier for the type of query being executed.",
 									},
 									"model": {
-										Required:    true,
-										Type:        schema.TypeString,
-										Description: "Custom JSON data to send to the specified datasource when querying.",
+										Required:     true,
+										Type:         schema.TypeString,
+										Description:  "Custom JSON data to send to the specified datasource when querying.",
+										ValidateFunc: validateModelJSON,
```
Comment (julienduchesne) [inline internal/resources/grafana/resource_alerting_rule_group.go]:
```suggestion
										ValidateFunc: validation.StringIsJSON,
```

You can use the standard validation lib for that 

`"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"`

File: internal/resources/grafana/resource_alerting_rule_group.go [hunk 2]
```diff
@@ -372,6 +375,7 @@ func packRuleData(queries []*gapi.AlertQuery) (interface{}, error) {
 		if queries[i] == nil {
 			continue
 		}
+		log.Printf("[DEBUG] PACKING!!!\n")
```
Comment (alexweav) [inline internal/resources/grafana/resource_alerting_rule_group.go]: Nit: We should probably drop this one before submit :smile:

the others are :+1:

File: internal/resources/grafana/resource_alerting_rule_group.go [hunk 3]
```diff
@@ -422,6 +426,49 @@ func unpackRuleData(raw interface{}) ([]*gapi.AlertQuery, error) {
 	return result, nil
 }
 
+// normalizeModelJSON is the StateFunc for the `model`. It removes well-known default
+// values from the model json, so that users do not see perma-diffs when not specifying
+// the values explicitly in their Terraform.
+func normalizeModelJSON(model interface{}) string {
```
Comment (alexweav) [inline internal/resources/grafana/resource_alerting_rule_group.go:431]: We could consider adding an automated test for this.

The tests are all integration tests with actual .tf files, and they all implicitly verify that `plan` is empty when the tests are done. So, you could do this quickly by changing an existing test to have these fields missing.

The .tf files used in tests are in this dir: https://github.com/grafana/terraform-provider-grafana/tree/master/examples/resources/grafana_rule_group

**Review by alexweav — APPROVED** [review]
My comments are very nitpicky, this is looking good

**Review by julienduchesne — APPROVED** [review]
A test sending over a minimal json model would be nice. It would also find new default fields in the future as well. But it LGTM either way!

File: internal/resources/grafana/resource_alerting_rule_group.go (hunk 3 above)
Comment (alexweav) [reply internal/resources/grafana/resource_alerting_rule_group.go:431]: Julien's suggestion of a totally new test using extremely minimal JSON might be better long term :smile:

File: internal/resources/grafana/resource_alerting_rule_group.go (hunk 2 above)
Comment (stevesg) [reply internal/resources/grafana/resource_alerting_rule_group.go]: Hahaha.... oops.

**Comment by JacobsonMT** [comment]
~I'm having some trouble verifying this fix. I'm still getting the issue~ Nevermind, user issue. Looks good!

**Review by JacobsonMT — APPROVED** [review]

**Comment by stevesg** [comment]
Thanks folks - I'll add some tests shortly.
