### PR TITLE
Force recomputation of computed values for Grafana Cloud stacks on slug update

### LINKED ISSUE #1191: Update slug of grafana_cloud_stack does not update computed attributes of the resource
### Terraform Version
* Terraform: 1.6.5
* Terraform Grafana Provider: 2.6.1

### Affected Resource(s)
* grafana_cloud_stack

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "2.6.1"
    }
  }
}

provider "grafana" {}

resource "grafana_cloud_stack" "stefano" {
  slug        = "stefanoboriero1"
  name        = "stefanoboriero1.grafana.net"
  region_slug = "prod-eu-west-2"
}

output "grafana_url_for_stack" {
    value = grafana_cloud_stack.stefano.url
}
```

### Steps to Reproduce
1. Assume the stack stefanoboriero1 is in place, otherwise apply the config as is
2. The output of the example is `stefanoboriero1.grafana.net`
3. Change the slug and name of the grafana_cloud_stack.stefano resource to
```hcl
resource "grafana_cloud_stack" "stefano" {
  slug        = "stefanoboriero2"
  name        = "stefanoboriero2.grafana.net"
  region_slug = "prod-eu-west-2"
}
```
4. Run `terraform apply`

### Expected Behavior
Upon running the apply command, the output should be `stefanoboriero2.grafana.net`.

### Actual Behavior
The output is still `stefanoboriero1.grafana.net`. If I apply again a second time, the computed attributes are adjusted with the upstream resource when terraform performs a read operation to refresh the state.

To clarify, this is for all computed attributes of the terraform grafana_cloud_stack resource, I used the `url` one to exemplify

### PR DESCRIPTION
**Pull request by stefanoboriero**
Names of some attributes of the Grafana Cloud stack depend on the slug of the stack. While the current state of the provider does update these attributes on the resource in the state, if these attributes are referenced in an output clause, the absence of a change in the generated plan renders the change unnoticed and stale information is outputted on a first apply. By using https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff it's possible to mark these values to be computed again if the slug changes, thus being reflected as changes in the plan and generated an up to date output.

Fixes #1191

### CODE REVIEW

File: internal/resources/cloud/resource_cloud_stack.go [hunk 1]
```diff
@@ -225,7 +226,24 @@ available at “https://<stack_slug>.grafana.net".`,
 				Computed: true,
 			},
 		},
-	}
+    CustomizeDiff: customdiff.All(
```
Comment (julienduchesne) [inline internal/resources/cloud/resource_cloud_stack.go]: There's a formatting error here:
```
internal/resources/cloud/resource_cloud_stack.go:229: File is not `goimports`-ed (goimports)
```

**Review by julienduchesne — APPROVED** [review]
LGTM! Thanks!
