### PR TITLE
Oncall Integration: Fix removing templates

### LINKED ISSUE #1199: Plugin did not respond on 2.7.0 only - grafana_oncall_integration change results in panic
### Terraform Version
* Terraform: **1.1.9**
* Terraform Grafana Provider: **2.7.0**
* Grafana: **Cloud**

### Affected Resource(s)
* grafana_oncall_integration

### Debug Output
I cannot provide the entire output.

### Panic Output
I cannot provide the entire output, [but I can give an extract](https://gist.github.com/GologicGClaudel/f75d40024ed8cd59675575526bad2e9a)

### Expected Behavior
During the `terraform plan` The Grafana OnCall Integration should show the expected changes

### Actual Behavior
The planned changes were not showed for the OnCall Integration and terraform crashed.

### Steps to Reproduce
1. Create a grafana_oncall_integration with some templates
2. (Optional ?) Create a grafana_oncall_escalation_chain and its grafana_oncall_escalation
3. `terraform apply`
4. Remove one of the message templates in the integration (or probably just make any change in the integration resource)
5. `terraform plan`

### Important Factoids
- This issue only appears in the version **2.7.0**. The bug disappeared once I changed the provider for 2.6.1 or lower.

### References
I've noticed that searching for `grpc` in the issue search bar shows multiple similar issues. I don't know if it's exactly the same but it looks like it.
- https://github.com/grafana/terraform-provider-grafana/issues/1067
- https://github.com/grafana/terraform-provider-grafana/issues/674

### PR DESCRIPTION
**Pull request by julienduchesne**
Closes https://github.com/grafana/terraform-provider-grafana/issues/1199 
This was broken in https://github.com/grafana/terraform-provider-grafana/pull/1185 
I added a test so that it doesn't occur again

### CODE REVIEW

File: internal/resources/oncall/resource_integration.go [hunk 1]
```diff
@@ -218,7 +222,7 @@ func ResourceIntegration() *schema.Resource {
 						return false
 					}
 					for k, v := range oldTemplateMap {
-						if newTemplateMap[k] != v {
+						if fmt.Sprintf("%v", newTemplateMap[k]) != fmt.Sprintf("%v", v) {
```
Comment (inkel) [inline internal/resources/oncall/resource_integration.go:228]: This is a bit convoluted. I'm approving because I eventually understood it, but it took me a short while.

**Review by inkel — APPROVED** [review]

File: internal/resources/oncall/resource_integration.go (hunk 1 above)
Comment (julienduchesne) [reply internal/resources/oncall/resource_integration.go:228]: I explained it!
