### PR TITLE
Validate that clients exist in all resources

### LINKED ISSUE #610: Unable to create contact points - unsupported protocol scheme """
### Terraform Version
* Terraform: 1.2.7
* Terraform Grafana Provider: 1.27.0
* Grafana: 9.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_contact_point

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "grafana" {
  cloud_api_url = "https://xxxxxx.grafana.net"
}

resource "grafana_contact_point" "my_contact_point" {
    name = "My Contact Point"

   email {
        addresses = ["one@company.org", "two@company.org"]
        message = "{{ len .Alerts.Firing }} firing."
        subject = "{{ template \"default.title\" .}}"
        single_email = true
        disable_resolve_message = false
    }
}
```

### Debug Output

```
2022-08-25T12:58:26.603+0100 [INFO]  Starting apply for module.project_grafana.grafana_contact_point.my_contact_point
2022-08-25T12:58:26.604+0100 [DEBUG] module.project_grafana.grafana_contact_point.my_contact_point: applying the planned Create change
2022-08-25T12:58:26.607+0100 [INFO]  provider.terraform-provider-grafana_v1.27.0: 2022/08/25 12:58:26 [ERROR] Grafana API Request error: &errors.errorString{s:"unsupported protocol scheme \"\""}: timestamp=2022-08-25T12:58:26.607+0100
2022-08-25T12:58:31.608+0100 [INFO]  provider.terraform-provider-grafana_v1.27.0: 2022/08/25 12:58:31 [ERROR] Grafana API Request error: &errors.errorString{s:"unsupported protocol scheme \"\""}: timestamp=2022-08-25T12:58:31.607+0100
```

### Panic Output

N/A

### Expected Behavior

Contact point created

### Actual Behavior

Creation fails with error "Error: Post "/api/v1/provisioning/contact-points": unsupported protocol scheme """

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Grafana is running in Grafana Cloud.

### References

N/A

### PR DESCRIPTION
**Pull request by julienduchesne**
This is a long standing issue, since we started using the provider for multiple things (SM, Grafana, Cloud, Oncall)
You can now configure your provider in a way that is valid but not for the resources you are using
Example, configuring a cloud provider but using a Grafana resource

The OnCall team added a validation on all of their resources, which works but is a bit tedious
This PR adds a validation on every resource, the corresponding client has to exist at read and create time

Here's what an error looks like:
```
│ Error: the Grafana client is required for `grafana_data_source`. Set the auth and url provider attributes
│
│   with grafana_data_source.elasticsearch-arbitrary,
│   on test-2022-08-24-datasources.tf line 14, in resource "grafana_data_source" "elasticsearch-arbitrary":
│   14: resource "grafana_data_source" "elasticsearch-arbitrary" {
```

Instead of `Error: Post "/api/v1/provisioning/contact-points": unsupported protocol scheme ""`

Fixes #610

### CODE REVIEW

File: grafana/provider.go [hunk 1]
```diff
@@ -44,6 +44,102 @@ func init() {
 }
 
 func Provider(version string) func() *schema.Provider {
+	var (
```
Comment (inkel) [inline grafana/provider.go:47]: Love this, makes the resource grouping much nicer to look at 👏🏽

File: grafana/provider.go [hunk 2]
```diff
@@ -159,87 +255,14 @@ func Provider(version string) func() *schema.Provider {
...
-				"grafana_oncall_on_call_shift":    ResourceOnCallOnCallShift(),
-				"grafana_oncall_schedule":         ResourceOnCallSchedule(),
-				"grafana_oncall_outgoing_webhook": ResourceOnCallOutgoingWebhook(),
-			},
+			ResourcesMap: mergeResourceMaps(
+				// Special case, this resource supports both Grafana and Cloud (depending on context)
+				map[string]*schema.Resource{
+					"grafana_api_key": ResourceAPIKey(),
+				},
+				grafanaClientResources, smClientResources, onCallClientResources, cloudClientResources),
```
Comment (inkel) [inline grafana/provider.go]: Nit: how about placing each group in separated lines? This way if in the future we need to add another group the diff will be easier to read.
```suggestion
				grafanaClientResources,
				smClientResources,
				onCallClientResources,
				cloudClientResources,
			),
```

File: grafana/provider.go [hunk 3]
```diff
@@ -159,87 +255,14 @@ func Provider(version string) func() *schema.Provider {
...
-				"grafana_oncall_user":             DataSourceOnCallUser(),
-				"grafana_oncall_escalation_chain": DataSourceOnCallEscalationChain(),
-				"grafana_oncall_schedule":         DataSourceOnCallSchedule(),
-				"grafana_oncall_slack_channel":    DataSourceOnCallSlackChannel(),
-				"grafana_oncall_action":           DataSourceOnCallAction(), // deprecated
-				"grafana_oncall_outgoing_webhook": DataSourceOnCallOutgoingWebhook(),
-				"grafana_oncall_user_group":       DataSourceOnCallUserGroup(),
-				"grafana_oncall_team":             DataSourceOnCallTeam(),
-			},
+			DataSourcesMap: mergeResourceMaps(grafanaClientDatasources, smClientDatasources, onCallClientDatasources, cloudClientDatasources),
```
Comment (inkel) [inline grafana/provider.go]: Same as above.

File: grafana/provider_validation.go [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+	"fmt"
+	"log"
+
+	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
+)
+
+// This file contains validations functions that can be added to a map of resources.
+// These validations are added to the Create and Read functions of all resources,
+//   because they are entrypoints (code that will be run in all cases).
```
Comment (inkel) [inline grafana/provider_validation.go]: Nit: the indentation of the comment is off.

**Review by inkel — APPROVED** [review]
This is a pretty clever idea, fantastic work!
