### PR TITLE
fix(cloud-stack): region_slug add new regions

### LINKED ISSUE #705: grafana_cloud_stack support Singapore region
### Terraform Version
* Terraform: v1.3.3
* Terraform Grafana Provider: 1.30.0
* Grafana: -

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_cloud_stack

### Terraform Configuration Files
```hcl
resource "grafana_cloud_stack" "this" {
  provider = grafana.cloud
  name = "xxx.grafana.net"
  slug = "xxx"
  description = "My description"
  region_slug = "prod-ap-southeast-0"
}
```

### Debug Output
```
Error: expected region_slug to be one of [au eu us], got prod-ap-southeast-0
```

### Expected Behavior
Should be applied without error when input region_slug with prod-ap-southeast-0 (Singapore).
Screenshot 2022-10-29 031148

### Actual Behavior
Error when input region_slug with prod-ap-southeast-0 (Singapore).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_cloud_stack.go have ValidateFunc not cover the new Singapore region.

Screenshot 2022-10-29 024413

I import the state from manual creation in Grafana Cloud GUI with the Singapore region and try to change it with another region. The result is below.
image

### PR DESCRIPTION
**Pull request by Eji4h**
add region prod-ap-southeast-0(GCP Singapore), prod-gb-south-0(GCP UK), prod-ap-south-0(GCP India), prod-sa-east-0(GCP Brazil)

Fix #705

### CODE REVIEW

File: grafana/resource_cloud_stack.go [hunk 1]
```diff
@@ -69,8 +69,10 @@ available at “https://<stack_slug>.grafana.net".`,
 				Optional: true,
 				ForceNew: true,
 				Description: `Region slug to assign to this stack.
-Changing region will destroy the existing stack and create a new one in the desired region`,
-				ValidateFunc: validation.StringInSlice([]string{"au", "eu", "us"}, false),
+Changing region will destroy the existing stack and create a new one in the desired region.
+Available input au(GCP Australia), eu(GCP Belgium), us(GCP US Central), prod-ap-southeast-0(GCP Singapore), prod-gb-south-0(GCP UK), prod-ap-south-0(GCP India), prod-sa-east-0(GCP Brazil)
```
Comment (julienduchesne) [inline grafana/resource_cloud_stack.go]: Nit: Can you add spaces before parentheses?
```suggestion
Available input au (GCP Australia), eu (GCP Belgium), us (GCP US Central), prod-ap-southeast-0 (GCP Singapore), prod-gb-south-0 (GCP UK), prod-ap-south-0 (GCP India), prod-sa-east-0 (GCP Brazil)
```

**Review by julienduchesne — APPROVED** [review]
👍
