### PR TITLE
Synthetic Monitoring: Restrict invalid labels

### LINKED ISSUE #541: `grafana_synthetic_monitoring_probe` could not get labels
### Terraform Version
* Terraform: `1.2.0`
* Terraform Grafana Provider: `1.24.0`
* Grafana: `8.0+`

### Affected Resource(s)
Please list the resources as a list, for example:
* `grafana_synthetic_monitoring_probe`
* `data.grafana_synthetic_monitoring_probes`

### Terraform Configuration Files
```hcl
data "grafana_synthetic_monitoring_probes" "this" {}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

* Running from CI so if you need I can show the output later.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

- No issues

### Actual Behavior
What actually happened?

```
│ Error: probe list request: status="500 Internal Server Error", msg="status: Internal Server Error, error: loading probe 2432: extracting probe labels: extracting label "0": expected name=value", err="loading probe 2432: extracting probe labels: extracting label "0": expected name=value"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
N/A

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
N/A

### PR DESCRIPTION
**Pull request by julienduchesne**
Restricting label names according to the prometheus data model: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
For the value, I found that commas and empty values are disallowed by the SM API (it returns a 500). @mem @grafana/synthetic-monitoring, any other characters that should be checked. I tried a bunch of weird stuff and all of it worked except commas
Fixes https://github.com/grafana/terraform-provider-grafana/issues/541

### CODE REVIEW

File: grafana/resource_synthetic_monitoring_probe.go [hunk 1]
```diff
@@ -80,6 +82,24 @@ Grafana Synthetic Monitoring Agent.
 				Elem: &schema.Schema{
 					Type: schema.TypeString,
 				},
+				ValidateDiagFunc: func(i interface{}, p cty.Path) diag.Diagnostics {
+					labelNameRegex := regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)
```
Comment (inkel) [inline grafana/resource_synthetic_monitoring_probe.go]: Can we initialize this outside the function?

File: grafana/resource_synthetic_monitoring_probe.go [hunk 2]
```diff
@@ -80,6 +82,24 @@ Grafana Synthetic Monitoring Agent.
...
+					for k, vInt := range i.(map[string]interface{}) {
+						if !labelNameRegex.MatchString(k) {
+							return diag.Errorf("invalid label name %q. Must match %s", k, labelNameRegex)
+						}
+
+						v := vInt.(string)
+						if v == "" {
+							return diag.Errorf("label %q has an empty value", k)
+						}
+						bannedChars := ","
```
Comment (inkel) [inline grafana/resource_synthetic_monitoring_probe.go]: This one could probably be made a constant 🤔

**Review by inkel — APPROVED** [review]
Leaving final approval to @mem @grafana/synthetic-monitoring  team.
