### PR TITLE
Fix inability to update managed ML alerts

### LINKED ISSUE #1681: [Bug]: Unable to Update a ML Alert after creation
### Terraform Version

1.8.5

### Terraform Grafana Provider Version

3.4.0

### Grafana Version

11.2.0

### Affected Resource(s)

* grafana_machine_learning_alert

### Terraform Configuration Files

```
  # module.grafana_supportlab_cloud_stack.grafana_machine_learning_alert.sm_probe_reachability_forecast will be updated in-place
  ~ resource "grafana_machine_learning_alert" "sm_probe_reachability_forecast" {
      ~ id                = "6d80ae7c-0b03-4fd6-940e-445cfa68d3eb" -> (known after apply)
      + labels            = {
          + "service" = "synthetics"
          + "source"  = "machine-learning"
        }
      ~ threshold         = ">0.75" -> ">0.5"
      ~ title             = "Synthetic Monitoring Reachability by Probe - Forecast" -> "Synthetic Monitoring Reachability by Probe Forecast - Anomalous"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.grafana_supportlab_cloud_stack.grafana_machine_learning_alert.sm_probe_reachability_forecast: Modifying... [id=6d80ae7c-0b03-4fd6-940e-445cfa68d3eb]
╷
│ Error: Unable to read resource
│ 
│   with module.grafana_supportlab_cloud_stack.grafana_machine_learning_alert.sm_probe_reachability_forecast,
│   on ../../../../as-code/terraform/modules/grafana_supportlab_cloud_stack/ml_synthetics.tf line 21, in resource "grafana_machine_learning_alert" "sm_probe_reachability_forecast":
│   21: resource "grafana_machine_learning_alert" "sm_probe_reachability_forecast" {
│ 
│ status: 400, body: {"status":"error","error":"unable to parse alert id as a UUID: invalid UUID length: 9"}
│ 
╵
```

### Expected Behavior

The `apply` should complete successfully and the resource updated with the changes.

### Actual Behavior

We get a 400 error.

However, it does seem the changes were made looking at the Alert in the UI.

### Steps to Reproduce

1. Create a ML Alert with TF
2. Apply It
3. Update the TF (Change the title or add a label, etc).
4. Try and apply it now, observe an error.

### Important Factoids

It does seem the changes were made to the Alert Rule itself.

### References

_No response_

### PR DESCRIPTION
**Pull request by csmarchbanks**
The ID field was not being populated by the plan so we were attempting
to create a new alert instead of updating the existing alert. Adding the
UseStateForUnknown plan modifier fixes this.

Fixes: #1681

### CODE REVIEW

File: internal/resources/machinelearning/resource_alert.go [hunk 1]
```diff
@@ -277,6 +277,13 @@ func (r *alertResource) Update(ctx context.Context, req resource.UpdateRequest,
 	if resp.Diagnostics.HasError() {
 		return
 	}
+	// It is required to fetch the ID from the state data. It is not present in the plan data.
```
Comment (julienduchesne) [inline internal/resources/machinelearning/resource_alert.go]: You can use the `UseStateForUnknown` modifier on the id attribute instead: https://github.com/grafana/terraform-provider-grafana-adaptive-metrics/blob/main/internal/provider/segment_resource.go#L59-L61

Comment (csmarchbanks) [reply internal/resources/machinelearning/resource_alert.go]: Ohh thanks! I have updated the PR to use this.

**Review by julienduchesne — APPROVED** [review]
